## Travis configuration file for T3PRF

language: r

sudo: required

warnings_are_errors: false

r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

r_packages:
 - devtools
 - testthat
 - RcppEigen

r_github_packages:
 - hadley/devtools
 - hadley/testthat

notifications:
 email:
  on_success: always
  on_failure: always
